services:
  greenlight:
    image: postgres:15-alpine
    container_name: greenlight-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${GREENLIGHT_DB_USERNAME}
      POSTGRES_PASSWORD: ${GREENLIGHT_DB_PASSWORD}
      POSTGRES_DB: ${GREENLIGHT_DB_DATABASE}
      GREENLIGHT_DB_DSN: ${GREENLIGHT_DB_DSN}
    ports:
      - "${GREENLIGHT_DB_PORT}:5432"
    volumes:
      - greenlight_volume:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  greenlight_volume: